//! Low-level utilities for the Python integration layer.
//!
//! This module contains helpers that are shared by the rest of the `python`
//! crate but have no direct user-facing API:
//!
//! * **Path conversion** – turning a [`Path`] into the `String` Python expects.
//! * **Error conversion** – mapping [`pyo3::PyErr`] to [`std::io::Error`].
//! * **Pickle serialisation** – converting arbitrary Python objects through
//!   Python's built-in `pickle` module so that they can be stored on disk or
//!   sent over a channel as raw bytes.
//! * **Outcome class registration** – storing a reference to the user-supplied
//!   Python outcome *class* so that [`CSVWritable::header`](tantale_core::CSVWritable::header)
//!   can call its `csv_header()` static method.
//! * **`init_python!` macro** – the public entry point that users call once in
//!   `main.rs` to wire a Python function into a Tantale experiment.

use std::{io::Error, path::Path};

use pyo3::{
    Py, PyAny, PyErr, PyResult, Python,
    types::{PyAnyMethods, PyBytes},
};

use crate::PY_OUTCOME_CLASS;

/// Converts a [`Path`] to an owned [`String`].
///
/// Returns [`std::io::Error`] if the path is not valid.
pub(crate) fn path_to_str(path: &Path) -> std::io::Result<String> {
    path.to_str()
        .ok_or_else(|| Error::other(format!("{} is not a valid path", path.display())))
        .map(str::to_owned)
}

/// Converts a [`pyo3::PyErr`] into a [`std::io::Error`].
pub(crate) fn py_to_io(e: PyErr) -> Error {
    Error::other(e.to_string())
}

/// Serialises a Python object to bytes using Python's `pickle` module.
///
/// Equivalent to `pickle.dumps(obj)`.  The resulting bytes can be stored on
/// disk, sent over a channel, or handed to [`pickle_loads`] to reconstruct the
/// original object.
///
/// # Errors
/// Propagates any [`PyErr`] raised by the Python interpreter (e.g. if the
/// object is not picklable).
pub(crate) fn pickle_dumps(py: Python<'_>, obj: &Py<PyAny>) -> PyResult<Vec<u8>> {
    let pickle = py.import("pickle")?;
    pickle
        .call_method1("dumps", (obj.bind(py),))?
        .extract::<Vec<u8>>()
}

/// Deserialises a Python object from bytes using Python's `pickle` module.
///
/// Equivalent to `pickle.loads(bytes)`.  The bytes must have been produced
/// by [`pickle_dumps`] or by Python's own `pickle.dumps`.
///
/// # Errors
/// Propagates any [`PyErr`] raised by the Python interpreter.
pub(crate) fn pickle_loads(py: Python<'_>, bytes: &[u8]) -> PyResult<Py<PyAny>> {
    let pickle = py.import("pickle")?;
    Ok(pickle
        .call_method1("loads", (PyBytes::new(py, bytes),))?
        .unbind())
}

/// Registers the Python outcome class used by [`CSVWritable::header`](tantale_core::CSVWritable::header) for [`PyOutcome`](crate::PyOutcome).
///
/// The class must expose a `@staticmethod csv_header() -> list[str]` and
/// an instance method `csv_write(self) -> list[str]`.
pub fn register_outcome(cls: Py<PyAny>) {
    PY_OUTCOME_CLASS
        .set(cls)
        .expect("Failed to register Python outcome class: a class has already been registered");
}

/// Wires a Python objective function into a Tantale experiment, fully implementing
/// [`Outcome`](tantale_core::Outcome) and optionally [`FidOutcome`](tantale_core::FidOutcome).
///
/// This macro must be called **once**, before any worker threads or processes are spawned.
/// It performs three tasks:
/// 1. Registers the `pytantale` pyo3 module (generated by `pyhpo!`) via
///    [`pyo3::append_to_inittab!`](https://pyo3.rs/main/doc/pyo3/macro.append_to_inittab).
/// 2. Loads the Python outcome class and calls [`register_outcome`].
/// 3. Loads the Python callable, registers it, and returns a typed Tantale
///    [`Objective`](tantale_core::Objective) or [`Stepped`](tantale_core::Stepped).
///
/// # How it works
///
/// Because [`Outcome::Cod`](tantale_core::Outcome) is an associated type (only one `impl Outcome`
/// per type), this macro generates a **local newtype** wrapping [`PyOutcome`](crate::PyOutcome) or
/// [`PyFidOutcome`](crate::PyFidOutcome) and implements the correct [`Codomain`](tantale_core::Codomain)
/// variant based on the objectives, constraints, cost, and step you declare.
/// The newtype is block-scoped and its type is inferred by the compiler.
///
/// # Syntax
///
/// ```rust,ignore
/// init_python!(
///     <kind>,
///     <searchspace_module>,
///     "<func_file>", "<func_module>", "<func_name>",
///     "<out_file>",  "<out_module>",  "<out_name>",
///     objectives: [<dir> "<attr>" $(, <dir> "<attr>")* ],
///     // for Stepped only:
///     step: "<step_attr>",
///     // optional:
///     constraints: ["<attr>" $(, "<attr>")* ],
///     cost: "<attr>",
/// )
/// ```
///
/// | Argument | Description |
/// |----------|-------------|
/// | `kind` | `Objective` (single-step) or `Stepped` (multi-fidelity). |
/// | `searchspace_module` | Rust path to the module containing the `pytantale` sub-module generated by `pyhpo!`. |
/// | `func_file` | Path to the Python source containing the objective, **relative to `CARGO_MANIFEST_DIR`**. |
/// | `func_module` | Python module name for `func_file`. |
/// | `func_name` | Name of the Python callable. |
/// | `out_file` | Path to the Python source containing the outcome class. May equal `func_file`. |
/// | `out_module` | Python module name for `out_file`. |
/// | `out_name` | Name of the Python outcome class. |
/// | `objectives` | One or more `maximize "attr"` / `minimize "attr"` entries. One entry > single-objective; two or more > multi-objective. |
/// | `step` | **Required for `Stepped`.** Attribute name of the [`PyStep`](crate::PyStep) field on the Python outcome. |
/// | `constraints` | *(Optional)* Attribute names of constraint fields (black-box, lower = less violation). |
/// | `cost` | *(Optional)* Attribute name of the evaluation cost field. |
///
/// # Return value
///
/// An `Objective<Arc<[MixedTypeDom]>, __Wrapper>` or `Stepped<Arc<[MixedTypeDom]>, __Wrapper, PyFuncState>`
/// where `__Wrapper` is an anonymous newtype generated by the macro.
///
/// # Examples
///
/// ```rust,ignore
/// // Single-objective, maximise "accuracy", no constraints, no cost
/// let obj = init_python!(
///     Objective, searchspace,
///     "/src/model.py", "model", "train",
///     "/src/model.py", "model", "MyOutcome",
///     objectives: [maximize "accuracy"],
/// );
///
/// // Multi-objective with constraints and cost
/// let obj = init_python!(
///     Objective, searchspace,
///     "/src/model.py", "model", "train",
///     "/src/model.py", "model", "MyOutcome",
///     objectives: [maximize "f1", minimize "latency"],
///     constraints: ["mem_usage"],
///     cost: "wall_time",
/// );
///
/// // Multi-fidelity single-objective
/// let obj = init_python!(
///     Stepped, searchspace,
///     "/src/model.py", "model", "train_stepped",
///     "/src/model.py", "model", "MyFidOutcome",
///     objectives: [maximize "accuracy"],
///     step: "step",
/// );
/// ```
#[macro_export]
macro_rules! init_python {
    // ============================================================
    // INTERNAL HELPERS
    // ============================================================

    // Load Python files, register outcome class and Objective callable.
    (@load_obj $ss:path, $ff:expr, $fm:expr, $fn_:expr, $of:expr, $om:expr, $on:expr) => {
        {use tantale::python::pyo3::{ffi::c_str, types::PyAnyMethods};
        use $ss::{pytantale};
        tantale::python::pyo3::append_to_inittab!(pytantale);
        tantale::python::pyo3::Python::attach(|py| {
            let out_src = c_str!(include_str!(concat!(env!("CARGO_MANIFEST_DIR"), $of)));
            let cls = tantale::python::pyo3::types::PyModule::from_code(
                py, out_src, c_str!($of), c_str!($om),
            )?.getattr($on)?.unbind();
            tantale::python::register_outcome(cls);
            let func_src = c_str!(include_str!(concat!(env!("CARGO_MANIFEST_DIR"), $ff)));
            let callable = tantale::python::pyo3::types::PyModule::from_code(
                py, func_src, c_str!($ff), c_str!($fm),
            )?.getattr($fn_)?.unbind();
            tantale::python::pyo3::PyResult::Ok(tantale::python::PyObjective::new(callable))
        }).unwrap()}
    };

    // Load Python files, register outcome class and Stepped callable.
    (@load_stepped $ss:path, $ff:expr, $fm:expr, $fn_:expr, $of:expr, $om:expr, $on:expr) => {
        {use tantale::python::pyo3::{ffi::c_str, types::PyAnyMethods};
        use $ss::{pytantale};
        tantale::python::pyo3::append_to_inittab!(pytantale);
        tantale::python::pyo3::Python::attach(|py| {
            let out_src = c_str!(include_str!(concat!(env!("CARGO_MANIFEST_DIR"), $of)));
            let cls = tantale::python::pyo3::types::PyModule::from_code(
                py, out_src, c_str!($of), c_str!($om),
            )?.getattr($on)?.unbind();
            tantale::python::register_outcome(cls);
            let func_src = c_str!(include_str!(concat!(env!("CARGO_MANIFEST_DIR"), $ff)));
            let callable = tantale::python::pyo3::types::PyModule::from_code(
                py, func_src, c_str!($ff), c_str!($fm),
            )?.getattr($fn_)?.unbind();
            tantale::python::pyo3::PyResult::Ok(tantale::python::PyStepped::new(callable))
        }).unwrap()}
    };

    // Delegate Debug / Serialize / Deserialize / CSVWritable to the inner PyOutcome.
    (@delegate_traits $wrap:ident, PyOutcome) => {
        impl ::std::fmt::Debug for $wrap {
            fn fmt(&self, f: &mut ::std::fmt::Formatter<'_>) -> ::std::fmt::Result {
                ::std::fmt::Debug::fmt(&self.0, f)
            }
        }
        impl ::serde::Serialize for $wrap {
            fn serialize<S: ::serde::Serializer>(&self, s: S) -> ::std::result::Result<S::Ok, S::Error> {
                ::serde::Serialize::serialize(&self.0, s)
            }
        }
        impl<'__de> ::serde::Deserialize<'__de> for $wrap {
            fn deserialize<D: ::serde::Deserializer<'__de>>(d: D) -> ::std::result::Result<Self, D::Error> {
                ::std::result::Result::Ok($wrap(::serde::Deserialize::deserialize(d)?))
            }
        }
        impl tantale::core::CSVWritable<(), ()> for $wrap {
            fn header(e: &()) -> ::std::vec::Vec<::std::string::String> {
                <tantale::python::PyOutcome as tantale::core::CSVWritable<(), ()>>::header(e)
            }
            fn write(&self, c: &()) -> ::std::vec::Vec<::std::string::String> {
                self.0.write(c)
            }
        }
    };

    // Delegate Debug / Serialize / Deserialize / CSVWritable to the inner PyFidOutcome.
    (@delegate_traits $wrap:ident, PyFidOutcome) => {
        impl ::std::fmt::Debug for $wrap {
            fn fmt(&self, f: &mut ::std::fmt::Formatter<'_>) -> ::std::fmt::Result {
                ::std::fmt::Debug::fmt(&self.0, f)
            }
        }
        impl ::serde::Serialize for $wrap {
            fn serialize<S: ::serde::Serializer>(&self, s: S) -> ::std::result::Result<S::Ok, S::Error> {
                ::serde::Serialize::serialize(&self.0, s)
            }
        }
        impl<'__de> ::serde::Deserialize<'__de> for $wrap {
            fn deserialize<D: ::serde::Deserializer<'__de>>(d: D) -> ::std::result::Result<Self, D::Error> {
                ::std::result::Result::Ok($wrap(::serde::Deserialize::deserialize(d)?))
            }
        }
        impl tantale::core::CSVWritable<(), ()> for $wrap {
            fn header(e: &()) -> ::std::vec::Vec<::std::string::String> {
                <tantale::python::PyFidOutcome as tantale::core::CSVWritable<(), ()>>::header(e)
            }
            fn write(&self, c: &()) -> ::std::vec::Vec<::std::string::String> {
                self.0.write(c)
            }
        }
    };

    // A `maximize` criteria: extract attribute and return it as-is (higher = better).
    (@criterion maximize, $attr:expr, $wrap:ident) => {
        (|o: &$wrap| o.0.getattr_f64($attr))
    };

    // A `minimize` criteria: extract attribute and negate it (Tantale always maximises).
    (@criterion minimize, $attr:expr, $wrap:ident) => {
        (|o: &$wrap| -o.0.getattr_f64($attr))
    };

    // Implement FidOutcome for a PyFidOutcome wrapper, reading the step from $step_attr.
    (@fid_outcome $wrap:ident, $step_attr:expr) => {
        use tantale::python::pyo3::types::PyAnyMethods;
        impl tantale::core::FidOutcome for $wrap {
            fn get_step(&self) -> tantale::core::EvalStep {
                tantale::python::pyo3::Python::attach(|py| {
                    self.0.0
                        .bind(py)
                        .getattr($step_attr)
                        .and_then(|s| Ok(s.extract::<tantale::python::PyStep>()?))
                        .map(|s| s.inner.into())
                        .unwrap_or_else(|_| tantale::core::EvalStep::error())
                })
            }
        }
    };

    // ============================================================
    // OBJECTIVE - single objective
    // ============================================================

    // 1. Single obj - no constraints, no cost > SingleCodomain
    (Objective, $ss:path,
     $ff:expr, $fm:expr, $fn_:expr,
     $of:expr, $om:expr, $on:expr,
     objectives: [$d0:ident $o0:expr] $(,)?
    ) => {{
        let objective = init_python!(@load_obj $ss, $ff, $fm, $fn_, $of, $om, $on);
        struct __PyOutWrapper(tantale::python::PyOutcome);
        impl tantale::python::PyOutWrap for __PyOutWrapper {
            fn wrap(py: tantale::python::pyo3::Python, obj: tantale::python::pyo3::Py<tantale::python::pyo3::PyAny>) -> Self{
                __PyOutWrapper(tantale::python::PyOutcome(obj))
            }
        }
        init_python!(@delegate_traits __PyOutWrapper, PyOutcome);
        impl tantale::core::Outcome for __PyOutWrapper {
            type Cod = tantale::core::SingleCodomain<Self>;
            fn codomain() -> Self::Cod {
                tantale::core::SingleCodomain::new(
                    init_python!(@criterion $d0, $o0, __PyOutWrapper)
                        as tantale::core::Criteria<Self>,
                )
            }
        }
        objective.register::<_, __PyOutWrapper>()
    }};

    // 2. Single obj - constraints only > ConstCodomain
    (Objective, $ss:path,
     $ff:expr, $fm:expr, $fn_:expr,
     $of:expr, $om:expr, $on:expr,
     objectives: [$d0:ident $o0:expr],
     constraints: [$($ca:expr),+ $(,)?] $(,)?
    ) => {{
        let objective = init_python!(@load_obj $ss, $ff, $fm, $fn_, $of, $om, $on);
        struct __PyOutWrapper(tantale::python::PyOutcome);
        impl tantale::python::PyOutWrap for __PyOutWrapper {
            fn wrap(py: tantale::python::pyo3::Python, obj: tantale::python::pyo3::Py<tantale::python::pyo3::PyAny>) -> Self{
                __PyOutWrapper(tantale::python::PyOutcome(obj))
            }
        }
        init_python!(@delegate_traits __PyOutWrapper, PyOutcome);
        impl tantale::core::Outcome for __PyOutWrapper {
            type Cod = tantale::core::ConstCodomain<Self>;
            fn codomain() -> Self::Cod {
                tantale::core::ConstCodomain::new(
                    init_python!(@criterion $d0, $o0, __PyOutWrapper)
                        as tantale::core::Criteria<Self>,
                    Box::new([
                        $(
                            (|o: &Self| o.0.getattr_f64($ca))
                                as tantale::core::Criteria<Self>
                        ),+
                    ]),
                )
            }
        }
        objective.register::<_, __PyOutWrapper>()
    }};

    // 3. Single obj - cost only > CostCodomain
    (Objective, $ss:path,
     $ff:expr, $fm:expr, $fn_:expr,
     $of:expr, $om:expr, $on:expr,
     objectives: [$d0:ident $o0:expr],
     cost: $co:expr $(,)?
    ) => {{
        let objective = init_python!(@load_obj $ss, $ff, $fm, $fn_, $of, $om, $on);
        struct __PyOutWrapper(tantale::python::PyOutcome);
        impl tantale::python::PyOutWrap for __PyOutWrapper {
            fn wrap(py: tantale::python::pyo3::Python, obj: tantale::python::pyo3::Py<tantale::python::pyo3::PyAny>) -> Self{
                __PyOutWrapper(tantale::python::PyOutcome(obj))
            }
        }
        init_python!(@delegate_traits __PyOutWrapper, PyOutcome);
        impl tantale::core::Outcome for __PyOutWrapper {
            type Cod = tantale::core::CostCodomain<Self>;
            fn codomain() -> Self::Cod {
                tantale::core::CostCodomain::new(
                    init_python!(@criterion $d0, $o0, __PyOutWrapper)
                        as tantale::core::Criteria<Self>,
                    (|o: &Self| o.0.getattr_f64($co)) as tantale::core::Criteria<Self>,
                )
            }
        }
        objective.register::<_, __PyOutWrapper>()
    }};

    // 4. Single obj - constraints + cost > CostConstCodomain
    (Objective, $ss:path,
     $ff:expr, $fm:expr, $fn_:expr,
     $of:expr, $om:expr, $on:expr,
     objectives: [$d0:ident $o0:expr],
     constraints: [$($ca:expr),+ $(,)?],
     cost: $co:expr $(,)?
    ) => {{
        let objective = init_python!(@load_obj $ss, $ff, $fm, $fn_, $of, $om, $on);
        struct __PyOutWrapper(tantale::python::PyOutcome);
        impl tantale::python::PyOutWrap for __PyOutWrapper {
            fn wrap(py: tantale::python::pyo3::Python, obj: tantale::python::pyo3::Py<tantale::python::pyo3::PyAny>) -> Self{
                __PyOutWrapper(tantale::python::PyOutcome(obj))
            }
        }
        init_python!(@delegate_traits __PyOutWrapper, PyOutcome);
        impl tantale::core::Outcome for __PyOutWrapper {
            type Cod = tantale::core::CostConstCodomain<Self>;
            fn codomain() -> Self::Cod {
                tantale::core::CostConstCodomain::new(
                    init_python!(@criterion $d0, $o0, __PyOutWrapper)
                        as tantale::core::Criteria<Self>,
                    (|o: &Self| o.0.getattr_f64($co)) as tantale::core::Criteria<Self>,
                    Box::new([
                        $(
                            (|o: &Self| o.0.getattr_f64($ca))
                                as tantale::core::Criteria<Self>
                        ),+
                    ]),
                )
            }
        }
        objective.register::<_, __PyOutWrapper>()
    }};

    // ============================================================
    // OBJECTIVE - multi-objective (2+ items in objectives:[…])
    // ============================================================

    // 5. Multi obj - no constraints, no cost > MultiCodomain
    (Objective, $ss:path,
     $ff:expr, $fm:expr, $fn_:expr,
     $of:expr, $om:expr, $on:expr,
     objectives: [$d0:ident $o0:expr, $($d:ident $o:expr),+ $(,)?] $(,)?
    ) => {{
        let objective = init_python!(@load_obj $ss, $ff, $fm, $fn_, $of, $om, $on);
        struct __PyOutWrapper(tantale::python::PyOutcome);
        impl tantale::python::PyOutWrap for __PyOutWrapper {
            fn wrap(py: tantale::python::pyo3::Python, obj: tantale::python::pyo3::Py<tantale::python::pyo3::PyAny>) -> Self{
                __PyOutWrapper(tantale::python::PyOutcome(obj))
            }
        }
        init_python!(@delegate_traits __PyOutWrapper, PyOutcome);
        impl tantale::core::Outcome for __PyOutWrapper {
            type Cod = tantale::core::MultiCodomain<Self>;
            fn codomain() -> Self::Cod {
                tantale::core::MultiCodomain::new(Box::new([
                    init_python!(@criterion $d0, $o0, __PyOutWrapper)
                        as tantale::core::Criteria<Self>,
                    $(
                        init_python!(@criterion $d, $o, __PyOutWrapper)
                            as tantale::core::Criteria<Self>
                    ),+
                ]))
            }
        }
        objective.register::<_, __PyOutWrapper>()
    }};

    // 6. Multi obj - constraints only > ConstMultiCodomain
    (Objective, $ss:path,
     $ff:expr, $fm:expr, $fn_:expr,
     $of:expr, $om:expr, $on:expr,
     objectives: [$d0:ident $o0:expr, $($d:ident $o:expr),+ $(,)?],
     constraints: [$($ca:expr),+ $(,)?] $(,)?
    ) => {{
        let objective = init_python!(@load_obj $ss, $ff, $fm, $fn_, $of, $om, $on);
        struct __PyOutWrapper(tantale::python::PyOutcome);
        impl tantale::python::PyOutWrap for __PyOutWrapper {
            fn wrap(py: tantale::python::pyo3::Python, obj: tantale::python::pyo3::Py<tantale::python::pyo3::PyAny>) -> Self{
                __PyOutWrapper(tantale::python::PyOutcome(obj))
            }
        }
        init_python!(@delegate_traits __PyOutWrapper, PyOutcome);
        impl tantale::core::Outcome for __PyOutWrapper {
            type Cod = tantale::core::ConstMultiCodomain<Self>;
            fn codomain() -> Self::Cod {
                tantale::core::ConstMultiCodomain::new(
                    Box::new([
                        init_python!(@criterion $d0, $o0, __PyOutWrapper)
                            as tantale::core::Criteria<Self>,
                        $(
                            init_python!(@criterion $d, $o, __PyOutWrapper)
                                as tantale::core::Criteria<Self>
                        ),+
                    ]),
                    Box::new([
                        $(
                            (|o: &Self| o.0.getattr_f64($ca))
                                as tantale::core::Criteria<Self>
                        ),+
                    ]),
                )
            }
        }
        objective.register::<_, __PyOutWrapper>()
    }};

    // 7. Multi obj - cost only > CostMultiCodomain
    (Objective, $ss:path,
     $ff:expr, $fm:expr, $fn_:expr,
     $of:expr, $om:expr, $on:expr,
     objectives: [$d0:ident $o0:expr, $($d:ident $o:expr),+ $(,)?],
     cost: $co:expr $(,)?
    ) => {{
        let objective = init_python!(@load_obj $ss, $ff, $fm, $fn_, $of, $om, $on);
        struct __PyOutWrapper(tantale::python::PyOutcome);
        impl tantale::python::PyOutWrap for __PyOutWrapper {
            fn wrap(py: tantale::python::pyo3::Python, obj: tantale::python::pyo3::Py<tantale::python::pyo3::PyAny>) -> Self{
                __PyOutWrapper(tantale::python::PyOutcome(obj))
            }
        }
        init_python!(@delegate_traits __PyOutWrapper, PyOutcome);
        impl tantale::core::Outcome for __PyOutWrapper {
            type Cod = tantale::core::CostMultiCodomain<Self>;
            fn codomain() -> Self::Cod {
                tantale::core::CostMultiCodomain::new(
                    Box::new([
                        init_python!(@criterion $d0, $o0, __PyOutWrapper)
                            as tantale::core::Criteria<Self>,
                        $(
                            init_python!(@criterion $d, $o, __PyOutWrapper)
                                as tantale::core::Criteria<Self>
                        ),+
                    ]),
                    (|o: &Self| o.0.getattr_f64($co)) as tantale::core::Criteria<Self>,
                )
            }
        }
        objective.register::<_, __PyOutWrapper>()
    }};

    // 8. Multi obj - constraints + cost > CostConstMultiCodomain
    (Objective, $ss:path,
     $ff:expr, $fm:expr, $fn_:expr,
     $of:expr, $om:expr, $on:expr,
     objectives: [$d0:ident $o0:expr, $($d:ident $o:expr),+ $(,)?],
     constraints: [$($ca:expr),+ $(,)?],
     cost: $co:expr $(,)?
    ) => {{
        let objective = init_python!(@load_obj $ss, $ff, $fm, $fn_, $of, $om, $on);
        struct __PyOutWrapper(tantale::python::PyOutcome);
        impl tantale::python::PyOutWrap for __PyOutWrapper {
            fn wrap(py: tantale::python::pyo3::Python, obj: tantale::python::pyo3::Py<tantale::python::pyo3::PyAny>) -> Self{
                __PyOutWrapper(tantale::python::PyOutcome(obj))
            }
        }
        init_python!(@delegate_traits __PyOutWrapper, PyOutcome);
        impl tantale::core::Outcome for __PyOutWrapper {
            type Cod = tantale::core::CostConstMultiCodomain<Self>;
            fn codomain() -> Self::Cod {
                tantale::core::CostConstMultiCodomain::new(
                    Box::new([
                        init_python!(@criterion $d0, $o0, __PyOutWrapper)
                            as tantale::core::Criteria<Self>,
                        $(
                            init_python!(@criterion $d, $o, __PyOutWrapper)
                                as tantale::core::Criteria<Self>
                        ),+
                    ]),
                    (|o: &Self| o.0.getattr_f64($co)) as tantale::core::Criteria<Self>,
                    Box::new([
                        $(
                            (|o: &Self| o.0.getattr_f64($ca))
                                as tantale::core::Criteria<Self>
                        ),+
                    ]),
                )
            }
        }
        objective.register::<_, __PyOutWrapper>()
    }};

    // ============================================================
    // STEPPED - single objective
    // ============================================================

    // 9. Stepped single obj - no constraints, no cost > SingleCodomain + FidOutcome
    (Stepped, $ss:path,
     $ff:expr, $fm:expr, $fn_:expr,
     $of:expr, $om:expr, $on:expr,
     objectives: [$d0:ident $o0:expr],
     step: $s:expr $(,)?
    ) => {{
        let objective = init_python!(@load_stepped $ss, $ff, $fm, $fn_, $of, $om, $on);
        struct __PyFidWrapper(tantale::python::PyFidOutcome);
        impl tantale::python::PyOutWrap for __PyFidWrapper {
            fn wrap(py: tantale::python::pyo3::Python, obj: tantale::python::pyo3::Py<tantale::python::pyo3::PyAny>) -> Self{
                __PyFidWrapper(tantale::python::PyFidOutcome(obj))
            }
        }
        init_python!(@delegate_traits __PyFidWrapper, PyFidOutcome);
        impl tantale::core::Outcome for __PyFidWrapper {
            type Cod = tantale::core::SingleCodomain<Self>;
            fn codomain() -> Self::Cod {
                tantale::core::SingleCodomain::new(
                    init_python!(@criterion $d0, $o0, __PyFidWrapper)
                        as tantale::core::Criteria<Self>,
                )
            }
        }
        init_python!(@fid_outcome __PyFidWrapper, $s);
        objective.register::<_, __PyFidWrapper>()
    }};

    // 10. Stepped single obj - constraints only > ConstCodomain + FidOutcome
    (Stepped, $ss:path,
     $ff:expr, $fm:expr, $fn_:expr,
     $of:expr, $om:expr, $on:expr,
     objectives: [$d0:ident $o0:expr],
     step: $s:expr,
     constraints: [$($ca:expr),+ $(,)?] $(,)?
    ) => {{
        let objective = init_python!(@load_stepped $ss, $ff, $fm, $fn_, $of, $om, $on);
        struct __PyFidWrapper(tantale::python::PyFidOutcome);
        impl tantale::python::PyOutWrap for __PyFidWrapper {
            fn wrap(py: tantale::python::pyo3::Python, obj: tantale::python::pyo3::Py<tantale::python::pyo3::PyAny>) -> Self{
                __PyFidWrapper(tantale::python::PyFidOutcome(obj))
            }
        }
        init_python!(@delegate_traits __PyFidWrapper, PyFidOutcome);
        impl tantale::core::Outcome for __PyFidWrapper {
            type Cod = tantale::core::ConstCodomain<Self>;
            fn codomain() -> Self::Cod {
                tantale::core::ConstCodomain::new(
                    init_python!(@criterion $d0, $o0, __PyFidWrapper)
                        as tantale::core::Criteria<Self>,
                    Box::new([
                        $(
                            (|o: &Self| o.0.getattr_f64($ca))
                                as tantale::core::Criteria<Self>
                        ),+
                    ]),
                )
            }
        }
        init_python!(@fid_outcome __PyFidWrapper, $s);
        objective.register::<_, __PyFidWrapper>()
    }};

    // 11. Stepped single obj - cost only > CostCodomain + FidOutcome
    (Stepped, $ss:path,
     $ff:expr, $fm:expr, $fn_:expr,
     $of:expr, $om:expr, $on:expr,
     objectives: [$d0:ident $o0:expr],
     step: $s:expr,
     cost: $co:expr $(,)?
    ) => {{
        let objective = init_python!(@load_stepped $ss, $ff, $fm, $fn_, $of, $om, $on);
        struct __PyFidWrapper(tantale::python::PyFidOutcome);
        impl tantale::python::PyOutWrap for __PyFidWrapper {
            fn wrap(py: tantale::python::pyo3::Python, obj: tantale::python::pyo3::Py<tantale::python::pyo3::PyAny>) -> Self{
                __PyFidWrapper(tantale::python::PyFidOutcome(obj))
            }
        }
        init_python!(@delegate_traits __PyFidWrapper, PyFidOutcome);
        impl tantale::core::Outcome for __PyFidWrapper {
            type Cod = tantale::core::CostCodomain<Self>;
            fn codomain() -> Self::Cod {
                tantale::core::CostCodomain::new(
                    init_python!(@criterion $d0, $o0, __PyFidWrapper)
                        as tantale::core::Criteria<Self>,
                    (|o: &Self| o.0.getattr_f64($co)) as tantale::core::Criteria<Self>,
                )
            }
        }
        init_python!(@fid_outcome __PyFidWrapper, $s);
        objective.register::<_, __PyFidWrapper>()
    }};

    // 12. Stepped single obj - constraints + cost > CostConstCodomain + FidOutcome
    (Stepped, $ss:path,
     $ff:expr, $fm:expr, $fn_:expr,
     $of:expr, $om:expr, $on:expr,
     objectives: [$d0:ident $o0:expr],
     step: $s:expr,
     constraints: [$($ca:expr),+ $(,)?],
     cost: $co:expr $(,)?
    ) => {{
        let objective = init_python!(@load_stepped $ss, $ff, $fm, $fn_, $of, $om, $on);
        struct __PyFidWrapper(tantale::python::PyFidOutcome);
        impl tantale::python::PyOutWrap for __PyFidWrapper {
            fn wrap(py: tantale::python::pyo3::Python, obj: tantale::python::pyo3::Py<tantale::python::pyo3::PyAny>) -> Self{
                __PyFidWrapper(tantale::python::PyFidOutcome(obj))
            }
        }
        init_python!(@delegate_traits __PyFidWrapper, PyFidOutcome);
        impl tantale::core::Outcome for __PyFidWrapper {
            type Cod = tantale::core::CostConstCodomain<Self>;
            fn codomain() -> Self::Cod {
                tantale::core::CostConstCodomain::new(
                    init_python!(@criterion $d0, $o0, __PyFidWrapper)
                        as tantale::core::Criteria<Self>,
                    (|o: &Self| o.0.getattr_f64($co)) as tantale::core::Criteria<Self>,
                    Box::new([
                        $(
                            (|o: &Self| o.0.getattr_f64($ca))
                                as tantale::core::Criteria<Self>
                        ),+
                    ]),
                )
            }
        }
        init_python!(@fid_outcome __PyFidWrapper, $s);
        objective.register::<_, __PyFidWrapper>()
    }};

    // ============================================================
    // STEPPED - multi-objective (2+ items in objectives:[…])
    // ============================================================

    // 13. Stepped multi obj - no constraints, no cost > MultiCodomain + FidOutcome
    (Stepped, $ss:path,
     $ff:expr, $fm:expr, $fn_:expr,
     $of:expr, $om:expr, $on:expr,
     objectives: [$d0:ident $o0:expr, $($d:ident $o:expr),+ $(,)?],
     step: $s:expr $(,)?
    ) => {{
        let objective = init_python!(@load_stepped $ss, $ff, $fm, $fn_, $of, $om, $on);
        struct __PyFidWrapper(tantale::python::PyFidOutcome);
        impl tantale::python::PyOutWrap for __PyFidWrapper {
            fn wrap(py: tantale::python::pyo3::Python, obj: tantale::python::pyo3::Py<tantale::python::pyo3::PyAny>) -> Self{
                __PyFidWrapper(tantale::python::PyFidOutcome(obj))
            }
        }
        init_python!(@delegate_traits __PyFidWrapper, PyFidOutcome);
        impl tantale::core::Outcome for __PyFidWrapper {
            type Cod = tantale::core::MultiCodomain<Self>;
            fn codomain() -> Self::Cod {
                tantale::core::MultiCodomain::new(Box::new([
                    init_python!(@criterion $d0, $o0, __PyFidWrapper)
                        as tantale::core::Criteria<Self>,
                    $(
                        init_python!(@criterion $d, $o, __PyFidWrapper)
                            as tantale::core::Criteria<Self>
                    ),+
                ]))
            }
        }
        init_python!(@fid_outcome __PyFidWrapper, $s);
        objective.register::<_, __PyFidWrapper>()
    }};

    // 14. Stepped multi obj - constraints only > ConstMultiCodomain + FidOutcome
    (Stepped, $ss:path,
     $ff:expr, $fm:expr, $fn_:expr,
     $of:expr, $om:expr, $on:expr,
     objectives: [$d0:ident $o0:expr, $($d:ident $o:expr),+ $(,)?],
     step: $s:expr,
     constraints: [$($ca:expr),+ $(,)?] $(,)?
    ) => {{
        let objective = init_python!(@load_stepped $ss, $ff, $fm, $fn_, $of, $om, $on);
        struct __PyFidWrapper(tantale::python::PyFidOutcome);
        impl tantale::python::PyOutWrap for __PyFidWrapper {
            fn wrap(py: tantale::python::pyo3::Python, obj: tantale::python::pyo3::Py<tantale::python::pyo3::PyAny>) -> Self{
                __PyFidWrapper(tantale::python::PyFidOutcome(obj))
            }
        }
        init_python!(@delegate_traits __PyFidWrapper, PyFidOutcome);
        impl tantale::core::Outcome for __PyFidWrapper {
            type Cod = tantale::core::ConstMultiCodomain<Self>;
            fn codomain() -> Self::Cod {
                tantale::core::ConstMultiCodomain::new(
                    Box::new([
                        init_python!(@criterion $d0, $o0, __PyFidWrapper)
                            as tantale::core::Criteria<Self>,
                        $(
                            init_python!(@criterion $d, $o, __PyFidWrapper)
                                as tantale::core::Criteria<Self>
                        ),+
                    ]),
                    Box::new([
                        $(
                            (|o: &Self| o.0.getattr_f64($ca))
                                as tantale::core::Criteria<Self>
                        ),+
                    ]),
                )
            }
        }
        init_python!(@fid_outcome __PyFidWrapper, $s);
        objective.register::<_, __PyFidWrapper>()
    }};

    // 15. Stepped multi obj - cost only > CostMultiCodomain + FidOutcome
    (Stepped, $ss:path,
     $ff:expr, $fm:expr, $fn_:expr,
     $of:expr, $om:expr, $on:expr,
     objectives: [$d0:ident $o0:expr, $($d:ident $o:expr),+ $(,)?],
     step: $s:expr,
     cost: $co:expr $(,)?
    ) => {{
        let objective = init_python!(@load_stepped $ss, $ff, $fm, $fn_, $of, $om, $on);
        struct __PyFidWrapper(tantale::python::PyFidOutcome);
        impl tantale::python::PyOutWrap for __PyFidWrapper {
            fn wrap(py: tantale::python::pyo3::Python, obj: tantale::python::pyo3::Py<tantale::python::pyo3::PyAny>) -> Self{
                __PyFidWrapper(tantale::python::PyFidOutcome(obj))
            }
        }
        init_python!(@delegate_traits __PyFidWrapper, PyFidOutcome);
        impl tantale::core::Outcome for __PyFidWrapper {
            type Cod = tantale::core::CostMultiCodomain<Self>;
            fn codomain() -> Self::Cod {
                tantale::core::CostMultiCodomain::new(
                    Box::new([
                        init_python!(@criterion $d0, $o0, __PyFidWrapper)
                            as tantale::core::Criteria<Self>,
                        $(
                            init_python!(@criterion $d, $o, __PyFidWrapper)
                                as tantale::core::Criteria<Self>
                        ),+
                    ]),
                    (|o: &Self| o.0.getattr_f64($co)) as tantale::core::Criteria<Self>,
                )
            }
        }
        init_python!(@fid_outcome __PyFidWrapper, $s);
        objective.register::<_, __PyFidWrapper>()
    }};

    // 16. Stepped multi obj - constraints + cost > CostConstMultiCodomain + FidOutcome
    (Stepped, $ss:path,
     $ff:expr, $fm:expr, $fn_:expr,
     $of:expr, $om:expr, $on:expr,
     objectives: [$d0:ident $o0:expr, $($d:ident $o:expr),+ $(,)?],
     step: $s:expr,
     constraints: [$($ca:expr),+ $(,)?],
     cost: $co:expr $(,)?
    ) => {{
        let objective = init_python!(@load_stepped $ss, $ff, $fm, $fn_, $of, $om, $on);
        struct __PyFidWrapper(tantale::python::PyFidOutcome);
        impl tantale::python::PyOutWrap for __PyFidWrapper {
            fn wrap(py: tantale::python::pyo3::Python, obj: tantale::python::pyo3::Py<tantale::python::pyo3::PyAny>) -> Self{
                __PyFidWrapper(tantale::python::PyFidOutcome(obj))
            }
        }
        init_python!(@delegate_traits __PyFidWrapper, PyFidOutcome);
        impl tantale::core::Outcome for __PyFidWrapper {
            type Cod = tantale::core::CostConstMultiCodomain<Self>;
            fn codomain() -> Self::Cod {
                tantale::core::CostConstMultiCodomain::new(
                    Box::new([
                        init_python!(@criterion $d0, $o0, __PyFidWrapper)
                            as tantale::core::Criteria<Self>,
                        $(
                            init_python!(@criterion $d, $o, __PyFidWrapper)
                                as tantale::core::Criteria<Self>
                        ),+
                    ]),
                    (|o: &Self| o.0.getattr_f64($co)) as tantale::core::Criteria<Self>,
                    Box::new([
                        $(
                            (|o: &Self| o.0.getattr_f64($ca))
                                as tantale::core::Criteria<Self>
                        ),+
                    ]),
                )
            }
        }
        init_python!(@fid_outcome __PyFidWrapper, $s);
        objective.register::<_, __PyFidWrapper>()
    }};
}
