//! Low-level utilities for the Python integration layer.
//!
//! This module contains helpers that are shared by the rest of the `python`
//! crate but have no direct user-facing API:
//!
//! * **Path conversion** – turning a [`Path`] into the `String` Python expects.
//! * **Error conversion** – mapping [`pyo3::PyErr`] to [`std::io::Error`].
//! * **Pickle serialisation** – converting arbitrary Python objects through
//!   Python's built-in `pickle` module so that they can be stored on disk or
//!   sent over a channel as raw bytes.
//! * **Outcome class registration** – storing a reference to the user-supplied
//!   Python outcome *class* so that [`CSVWritable::header`](tantale_core::CSVWritable::header)
//!   can call its `csv_header()` static method.
//! * **`init_python!` macro** – the public entry point that users call once in
//!   `main.rs` to wire a Python function into a Tantale experiment.

use std::{io::Error, path::Path};

use pyo3::{
    Py, PyAny, PyErr, PyResult, Python,
    types::{PyAnyMethods, PyBytes},
};

use crate::PY_OUTCOME_CLASS;

/// Converts a [`Path`] to an owned [`String`].
///
/// Returns [`std::io::Error`] if the path is not valid.
pub(crate) fn path_to_str(path: &Path) -> std::io::Result<String> {
    path.to_str()
        .ok_or_else(|| Error::other(format!("{} is not a valid path", path.display())))
        .map(str::to_owned)
}

/// Converts a [`pyo3::PyErr`] into a [`std::io::Error`].
pub(crate) fn py_to_io(e: PyErr) -> Error {
    Error::other(e.to_string())
}

/// Serialises a Python object to bytes using Python's `pickle` module.
///
/// Equivalent to `pickle.dumps(obj)`.  The resulting bytes can be stored on
/// disk, sent over a channel, or handed to [`pickle_loads`] to reconstruct the
/// original object.
///
/// # Errors
/// Propagates any [`PyErr`] raised by the Python interpreter (e.g. if the
/// object is not picklable).
pub(crate) fn pickle_dumps(py: Python<'_>, obj: &Py<PyAny>) -> PyResult<Vec<u8>> {
    let pickle = py.import("pickle")?;
    pickle
        .call_method1("dumps", (obj.bind(py),))?
        .extract::<Vec<u8>>()
}

/// Deserialises a Python object from bytes using Python's `pickle` module.
///
/// Equivalent to `pickle.loads(bytes)`.  The bytes must have been produced
/// by [`pickle_dumps`] or by Python's own `pickle.dumps`.
///
/// # Errors
/// Propagates any [`PyErr`] raised by the Python interpreter.
pub(crate) fn pickle_loads(py: Python<'_>, bytes: &[u8]) -> PyResult<Py<PyAny>> {
    let pickle = py.import("pickle")?;
    Ok(pickle
        .call_method1("loads", (PyBytes::new(py, bytes),))?
        .unbind())
}

/// Registers the Python outcome class used by [`CSVWritable::header`] for [`PyOutcome`].
///
/// The class must expose a `@staticmethod csv_header() -> list[str]` and
/// an instance method `csv_write(self) -> list[str]`.
pub fn register_outcome(cls: Py<PyAny>) {
    PY_OUTCOME_CLASS.with(|cell| *cell.borrow_mut() = Some(cls));
}

/// Wires a Python objective function into a Tantale experiment.
///
/// This macro must be called **once**, before any worker threads or processes are spawned,
/// to:
/// 1. Register the `pytantale` pyo3 module (generated by [`pyhpo!`](tantale::macros::pyhpo))
///    via [`pyo3::append_to_inittab!`](https://pyo3.rs/main/doc/pyo3/macro.append_to_inittab) so that Python code can `import pytantale`.
/// 2. Load the outcome class, call [`register_outcome`], and store it in the
///    thread-local [`PY_OUTCOME_CLASS`](crate::PY_OUTCOME_CLASS) for CSV output.
/// 3. Load the objective callable and return a typed Tantale
///    [`Objective`](tantale_core::Objective) or [`Stepped`](tantale_core::Stepped)
///    that can be passed directly to the optimizer builder.
///
/// # Syntax
///
/// ```rust,ignore
/// init_python!(
///     <function_kind>,
///     <searchspace_module>,
///     "<func_file>",   "<func_module>",   "<func_name>",
///     "<out_file>",    "<out_module>",    "<out_name>",
/// )
/// ```
///
/// | Argument | Description |
/// |----------|-------------|
/// | `function_kind` | Either `Objective` (single-step) or `Stepped` (multi-fidelity). |
/// | `searchspace_module` | Rust module path that contains the `pytantale` sub-module generated by [`pyhpo!`]. E.g. `searchspace`. |
/// | `func_file` | Path to the Python source file containing the objective function, **relative to `CARGO_MANIFEST_DIR`**. E.g. `"/src/model.py"`. |
/// | `func_module` | Python module name used when loading `func_file`. E.g. `"model"`. |
/// | `func_name` | Name of the Python callable to optimise. E.g. `"objective"`. |
/// | `out_file` | Path to the Python source file containing the outcome class, **relative to `CARGO_MANIFEST_DIR`**. May be the same file as `func_file`. |
/// | `out_module` | Python module name used when loading `out_file`. |
/// | `out_name` | Name of the Python outcome class. E.g. `"MyOutcome"`. |
///
/// # Return value
///
/// * `Objective` variant -> returns `Objective<Arc<[MixedTypeDom]>, PyOutcome>`
/// * `Stepped` variant  -> returns `Stepped<Arc<[MixedTypeDom]>, PyFidOutcome, PyFuncState>`
///
/// # Example
///
/// ```rust,ignore
/// use tantale::python::{PyFidOutcome, init_python};
///
/// pub mod searchspace;
///
/// fn main() {
///     let objective = init_python!(
///         Stepped,
///         searchspace,
///         "/src/model.py", "model", "objective",
///         "/src/model.py", "model", "MyOutcome",
///     );
///     // pass `objective` to the optimizer builder...
/// }
/// ```
#[macro_export]
macro_rules! init_python {
    (Objective, $searchspace_module:path, $func_file:expr, $func_module:expr, $func_name:expr, $out_file:expr, $out_module:expr, $out_name:expr) => {{
        use tantale::python::pyo3::{ffi::c_str, types::PyAnyMethods};
        use $searchspace_module::{pytantale,};

        tantale::python::pyo3::append_to_inittab!(pytantale);
        let objective = tantale::python::pyo3::Python::attach(|py| {
            let out_mod = c_str!(include_str!(concat!(env!("CARGO_MANIFEST_DIR"), $out_file)));
            let cls = tantale::python::pyo3::types::PyModule::from_code(
                py,
                out_mod,
                c_str!($out_file),
                c_str!($out_module),
            )?
            .getattr($out_name)?
            .unbind();
            tantale::python::register_outcome(cls);

            let func_mod = c_str!(include_str!(concat!(
                env!("CARGO_MANIFEST_DIR"),
                $func_file
            )));
            let callable = tantale::python::pyo3::types::PyModule::from_code(
                py,
                func_mod,
                c_str!($func_file),
                c_str!($func_module),
            )?
            .getattr($func_name)?
            .unbind();
            tantale::python::pyo3::PyResult::Ok(tantale::python::PyObjective::new(callable))
        })
        .unwrap();
        objective.register()
    }};
    (Stepped, $searchspace_module:path, $func_file:expr, $func_module:expr, $func_name:expr, $out_file:expr, $out_module:expr, $out_name:expr) => {{
        use std::ffi::CStr;
        use tantale::python::pyo3::{ffi::c_str, types::PyAnyMethods};
        use $searchspace_module::{pytantale,};

        tantale::python::pyo3::append_to_inittab!(pytantale);

        let objective = tantale::python::pyo3::Python::attach(|py| {
            let out_mod = c_str!(include_str!(concat!(env!("CARGO_MANIFEST_DIR"), $out_file)));
            let cls = tantale::python::pyo3::types::PyModule::from_code(
                py,
                out_mod,
                c_str!($out_file),
                c_str!($out_module),
            )?
            .getattr($out_name)?
            .unbind();
            tantale::python::register_outcome(cls);

            let func_mod = c_str!(include_str!(concat!(
                env!("CARGO_MANIFEST_DIR"),
                $func_file
            )));
            let callable = tantale::python::pyo3::types::PyModule::from_code(
                py,
                func_mod,
                c_str!($func_file),
                c_str!($func_module),
            )?
            .getattr($func_name)?
            .unbind();
            tantale::python::pyo3::PyResult::Ok(tantale::python::PyStepped::new(callable))
        })
        .unwrap();
        objective.register()
    }};
}
